# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure Maven
      run: |
        mvn --version

    - name: Build project
      run: mvn clean compile

    # Current possible values for env=[GITHUB,QA]
    - name: Test with Maven
      run: mvn -Denv=GITHUB test

    - name: Archive test results as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: target/results/
